/**
 * PHASE 8 — one-off bug filing pass over the homepage execution results from this
 * QA cycle. Run once after execution (not idempotent-safe to re-run blindly if bugs
 * have since been hand-edited) — see agents/homepage-bug-analyzer.md for the bar a
 * finding has to clear before it's filed here (observed + reproduced/evidenced, not
 * just a discovery-time heuristic hit).
 */
const fs = require('fs');
const path = require('path');
const { loadJson, saveJson } = require('../utils/qaState');

const bugs = [
  {
    id: 'BUG-HOME-001',
    title: 'Several product images on the homepage fail to load (403 / ORB-blocked from media-stage.thekanaa.com)',
    requirementId: 'REQ-HOME-034',
    sectionId: 'HOME-SEC-009',
    elementId: null,
    scenarioId: 'SC-HOME-034',
    testCaseId: 'TC-HOME-034',
    executionId: null, // filled in below from state/executions.json
    feature: 'Product widget images',
    environment: 'staging (dev-nx.thekanaa.com)',
    browser: 'chromium',
    viewport: '1280x800',
    buildVersion: 'unknown (dev-nx, captured 2026-09-14)',
    preconditions: 'Guest session, homepage loaded, scrolled so the affected widget is in view.',
    testData: 'N/A',
    stepsToReproduce: [
      'Go to https://dev-nx.thekanaa.com/en-sa/',
      'Scroll to the "Big adventures start with small steps" widget (and others — see notes).',
      'Observe several product tiles show a broken-image placeholder instead of the product photo.',
    ],
    expectedResult: 'Every product tile shows its product photo.',
    actualResult: '5 images consistently fail across two independent test runs (initial discovery and later execution): Maisto Rock Crawler R/C Car, Maisto 1:24 1929 Ford Model A, Maisto 1:24 1967 Ford Mustang GT, Disney Stitch Light-Up Yoyo, Pop Mart Labubu keychain — plus 2 non-product thirdlevelbanner images. Each fails with either a 403 from the site\'s own /_next/image proxy or net::ERR_BLOCKED_BY_ORB fetching the source directly from media-stage.thekanaa.com — same asset, same failure, both paths.',
    severity: 'Major',
    priority: 'P1',
    reproducibility: 'Always (reproduced identically across 2 independent full test runs, several hours apart)',
    screenshot: 'evidence/homepage/discovery/full-page-final.png',
    video: null,
    trace: 'evidence/homepage/discovery/trace.zip',
    consoleEvidence: null,
    networkEvidence: 'specs/homepage-test-plan.md (Network failures section) and evidence/homepage/discovery/network-failures.json',
    relatedRegressionTests: ['TC-HOME-016', 'TC-HOME-020', 'TC-HOME-027', 'TC-HOME-031', 'TC-HOME-037', 'TC-HOME-047'],
    notes: 'A wider set of product images intermittently showed naturalWidth=0 in later, longer test runs (deep into an 11+ minute sequential session). Not bundled into this bug\'s confirmed count — the pattern (later-indexed samples fail more) matches this project\'s already-documented IP-based throttling behavior for repeated automated requests against this dev environment (see README.md "Known site quirks"), not a distinct defect. Re-verify those specific instances with an isolated, freshly-started run before filing separately.',
    status: 'OPEN',
  },
  {
    id: 'BUG-HOME-002',
    title: 'Homepage triggers a cross-origin prefetch to production thekanaa.com that fails CORS, on every load',
    requirementId: null,
    sectionId: 'HOME-GLOBAL',
    elementId: null,
    scenarioId: null,
    testCaseId: 'TC-HOME-068',
    executionId: null,
    feature: 'Console & network health',
    environment: 'staging (dev-nx.thekanaa.com)',
    browser: 'chromium',
    viewport: '1280x800',
    buildVersion: 'unknown (dev-nx, captured 2026-09-14)',
    preconditions: 'Fresh guest session, no ad blocker.',
    testData: 'N/A',
    stepsToReproduce: [
      'Open browser devtools console and network tab.',
      'Go to https://dev-nx.thekanaa.com/en-sa/ and let it fully load (no further interaction needed).',
    ],
    expectedResult: 'No console errors on a clean homepage load; all first-party requests stay on dev-nx.thekanaa.com (or the site\'s own CDN) and succeed.',
    actualResult: 'A React Server Component prefetch for the "Pools & Outdoor" category redirects from dev-nx.thekanaa.com to the production apex domain thekanaa.com, which has no Access-Control-Allow-Origin header for that request — the browser blocks it, logging a CORS console error and a net::ERR_FAILED network failure. Reproduced identically on every one of 3 independent test runs.',
    severity: 'Medium',
    priority: 'P2',
    reproducibility: 'Always (every homepage load, 3/3 independent runs)',
    screenshot: null,
    video: null,
    trace: null,
    consoleEvidence: 'specs/homepage-test-plan.md (Console errors section)',
    networkEvidence: 'evidence/homepage/TC-HOME-068/console-network.json',
    relatedRegressionTests: ['TC-HOME-005'],
    notes: 'Likely an environment-config mismatch (a category redirect target still pointing at prod instead of dev-nx/mcstaging) rather than an application bug — worth routing to whoever owns the dev-nx environment config alongside the fix.',
    status: 'OPEN',
  },
  {
    id: 'BUG-HOME-003',
    title: 'mcstaging.thekanaa.com returns 503 for multiple homepage-linked pages; one link to it is additionally malformed',
    requirementId: null,
    sectionId: 'HOME-SEC-013',
    elementId: null,
    scenarioId: null,
    testCaseId: 'TC-HOME-045',
    executionId: null,
    feature: 'Homepage widget links',
    environment: 'staging (dev-nx.thekanaa.com / mcstaging.thekanaa.com)',
    browser: 'chromium',
    viewport: '1280x800',
    buildVersion: 'unknown (dev-nx, captured 2026-09-14)',
    preconditions: 'Guest session.',
    testData: 'N/A',
    stepsToReproduce: [
      'GET https://mcstaging.thekanaa.com/en-sa/about-us -> 503',
      'GET https://mcstaging.thekanaa.com/en-sa/toys-games/dolls-collectables.html?page=1 -> 503 (linked from the "Big adventures start with small steps" widget)',
      'Separately: inspect the "Ready set go" widget\'s DOM for a link with href="https:/mcstaging.thekanaa.com/en-sa/about-us" (single slash) — confirmed via a live browser check that this exact malformed href resolves to https://dev-nx.thekanaa.com/mcstaging.thekanaa.com/en-sa/about-us (a broken same-origin path) instead of the intended host.',
    ],
    expectedResult: 'Linked mcstaging pages return 200, and every href is a well-formed absolute URL.',
    actualResult: 'Two different mcstaging.thekanaa.com paths return 503 (reproduced across 2 runs); one homepage link to that host is malformed and would mis-navigate in a real browser.',
    severity: 'Medium',
    priority: 'P2',
    reproducibility: 'Always for the 503s (2/2 runs); the malformed href is static markup, not load-dependent',
    screenshot: null,
    video: null,
    trace: null,
    consoleEvidence: null,
    networkEvidence: 'evidence/homepage/TC-HOME-045/link-check.json, evidence/homepage/TC-HOME-033 (see state/executions.json for that run)',
    relatedRegressionTests: ['TC-HOME-033'],
    notes: 'The malformed-href link is currently hidden (display:none, no accessible name) — low real-world impact on its own, but worth fixing alongside the 503s since both point at the same subdomain. Node\'s URL parser normalizes the single-slash form leniently, which is why this was initially missed by an HTTP-only check — confirmed instead via a live Chromium a.href evaluation.',
    status: 'OPEN',
  },
  {
    id: 'BUG-HOME-004',
    title: 'QA/placeholder test products render live in homepage product widgets',
    requirementId: null,
    sectionId: 'HOME-GLOBAL',
    elementId: null,
    scenarioId: null,
    testCaseId: null,
    executionId: null,
    feature: 'Product catalog hygiene',
    environment: 'staging (dev-nx.thekanaa.com)',
    browser: 'chromium',
    viewport: '1280x800',
    buildVersion: 'unknown (dev-nx, captured 2026-09-14)',
    preconditions: 'None — visible on a guest homepage load, content depends on widget rotation.',
    testData: 'N/A',
    stepsToReproduce: [
      'Load the homepage and scroll through the product widgets (may require more than one load, since widget content rotates).',
      'Look for a product tile named "Testing product for label" or "Rental Test Product".',
    ],
    expectedResult: 'Only real, purchasable catalog products appear in homepage widgets.',
    actualResult: 'Two placeholder/test products were found rendering as ordinary tiles in live homepage widgets during discovery.',
    severity: 'Minor',
    priority: 'P3',
    reproducibility: 'Observed once at discovery time; widget content rotates so a fixed repro isn\'t guaranteed on demand',
    screenshot: 'evidence/homepage/discovery/full-page-final.png',
    video: null,
    trace: null,
    consoleEvidence: null,
    networkEvidence: null,
    relatedRegressionTests: [],
    notes: 'Catalog/CMS data-hygiene issue, not a code defect — route to whoever owns product/CMS content review.',
    status: 'OPEN',
  },
  {
    id: 'BUG-HOME-005',
    title: 'A homepage product widget has a blank section title',
    requirementId: 'REQ-HOME-043',
    sectionId: 'HOME-SEC-012',
    elementId: null,
    scenarioId: 'SC-HOME-043',
    testCaseId: 'TC-HOME-043',
    executionId: null,
    feature: 'Product widget heading',
    environment: 'staging (dev-nx.thekanaa.com)',
    browser: 'chromium',
    viewport: '1280x800',
    buildVersion: 'unknown (dev-nx, captured 2026-09-14)',
    preconditions: 'Guest session; scroll to the widget between "Deals Of The Week" and "Most Popular Products".',
    testData: 'N/A',
    stepsToReproduce: [
      'Load the homepage and scroll to the product widget located between "Deals Of The Week" and "Most Popular Products" (~5538px down the page at discovery time).',
      'Observe the widget renders its product row with no heading/title text above it.',
    ],
    expectedResult: 'Every product widget shows a title describing its contents.',
    actualResult: 'This widget consistently renders with an empty heading, reproduced on every run (it cannot be re-verified by heading text for that reason, so every execution against it is recorded FAIL by design — see agents/homepage-executor.md).',
    severity: 'Minor',
    priority: 'P3',
    reproducibility: 'Always (reproduced on every run so far)',
    screenshot: null,
    video: null,
    trace: null,
    consoleEvidence: null,
    networkEvidence: null,
    relatedRegressionTests: ['TC-HOME-043'],
    notes: null,
    status: 'OPEN',
  },
  {
    id: 'BUG-HOME-006',
    title: 'Header search box\'s suggestions request fails (404)',
    requirementId: 'REQ-HOME-005',
    sectionId: 'HOME-SEC-001',
    elementId: null,
    scenarioId: 'SC-HOME-005',
    testCaseId: 'TC-HOME-005',
    executionId: null,
    feature: 'Header search',
    environment: 'staging (dev-nx.thekanaa.com)',
    browser: 'chromium',
    viewport: '1280x800',
    buildVersion: 'unknown (dev-nx, captured 2026-09-14)',
    preconditions: 'Guest session, homepage loaded.',
    testData: 'Query text: "toys"',
    stepsToReproduce: [
      'Click the header search box.',
      'Type "toys".',
      'Open devtools console.',
    ],
    expectedResult: 'Search suggestions load without error (or the feature degrades silently with no console error).',
    actualResult: 'Console logs "Error fetching suggestions" backed by a 404 network response.',
    severity: 'Major',
    priority: 'P2',
    reproducibility: 'Observed once so far — recommend one more isolated confirmation run before treating as fully confirmed',
    screenshot: null,
    video: null,
    trace: 'evidence/homepage/TC-HOME-005/',
    consoleEvidence: 'evidence/homepage/TC-HOME-005/input-check.json',
    networkEvidence: null,
    relatedRegressionTests: [],
    notes: 'This homepage also independently triggers the pooloutdoor CORS error (BUG-HOME-002) while the search box is being tested, since both fire on/soon-after page load — the two are unrelated defects that happen to co-occur in the same console listener window.',
    status: 'OPEN',
  },
  {
    id: 'BUG-HOME-007',
    title: '8 homepage links have no accessible name',
    requirementId: null,
    sectionId: 'HOME-GLOBAL',
    elementId: null,
    scenarioId: null,
    testCaseId: 'TC-HOME-066',
    executionId: null,
    feature: 'Accessibility — accessible names',
    environment: 'staging (dev-nx.thekanaa.com)',
    browser: 'chromium',
    viewport: '1280x800',
    buildVersion: 'unknown (dev-nx, captured 2026-09-14)',
    preconditions: 'Guest session, homepage loaded, screen reader or accessibility tree inspection.',
    testData: 'N/A',
    stepsToReproduce: [
      'Load the homepage.',
      'Inspect the accessibility tree (or use a screen reader) over the header logo link and the hero/category-widget banner links.',
    ],
    expectedResult: 'Every link exposes a non-empty accessible name (visible text, aria-label, or meaningful image alt).',
    actualResult: '8 visible links have no accessible name: the header logo link (href="/en-sa/"), several hero-banner slide links, and a handful of category-widget banner links (see evidence for the full href list).',
    severity: 'Minor',
    priority: 'P3',
    reproducibility: 'Reproduced (same category of elements — header logo — every run; the exact widget-banner sample varies with content rotation)',
    screenshot: 'evidence/homepage/TC-HOME-066/final-focus-state.png',
    video: null,
    trace: null,
    consoleEvidence: null,
    networkEvidence: null,
    relatedRegressionTests: [],
    notes: 'A screen reader user has no way to know what these links do before activating them. Adding aria-label (e.g. "Kanaa home") would resolve the header logo case immediately.',
    status: 'OPEN',
  },
  {
    id: 'BUG-HOME-008',
    title: 'Two homepage section headings have malformed text',
    requirementId: null,
    sectionId: 'HOME-GLOBAL',
    elementId: null,
    scenarioId: null,
    testCaseId: null,
    executionId: null,
    feature: 'Homepage copy',
    environment: 'staging (dev-nx.thekanaa.com)',
    browser: 'chromium',
    viewport: '1280x800',
    buildVersion: 'unknown (dev-nx, captured 2026-09-14)',
    preconditions: 'None.',
    testData: 'N/A',
    stepsToReproduce: [
      'Load the homepage.',
      'Read the category-grid section heading: shows "Shop By Categorysssss".',
      'Read the deals-widget section heading: shows "Best Price Guarante" (missing the final "e").',
    ],
    expectedResult: '"Shop By Category" and "Best Price Guarantee".',
    actualResult: 'Both headings are confirmed malformed via the accessibility tree (not just a visual/rendering artifact) — "Shop By Categorysssss" and "Best Price Guarante".',
    severity: 'Trivial',
    priority: 'P3',
    reproducibility: 'Always — static template text, confirmed on every run',
    screenshot: null,
    video: null,
    trace: null,
    consoleEvidence: null,
    networkEvidence: null,
    relatedRegressionTests: [],
    notes: 'One product card badge was also observed reading "Best Pricee" (double e) during discovery — not included here since it\'s on a specific, dynamically-rotating product and wasn\'t re-confirmed on a later run; worth a spot-check if seen again.',
    status: 'OPEN',
  },
];

const executions = loadJson('executions.json');
function latestExecutionFor(testCaseId) {
  if (!testCaseId) return null;
  const matches = executions.filter((e) => e.testCaseId === testCaseId);
  return matches.length ? matches[matches.length - 1].id : null;
}
for (const bug of bugs) {
  bug.executionId = latestExecutionFor(bug.testCaseId);
}

saveJson('bugs.json', bugs);

const traceability = loadJson('traceability.json');
for (const bug of bugs) {
  if (!bug.testCaseId) continue;
  const row = traceability.find((t) => t.testCaseId === bug.testCaseId);
  if (row) {
    row.bugIds = row.bugIds || [];
    if (!row.bugIds.includes(bug.id)) row.bugIds.push(bug.id);
  }
}
saveJson('traceability.json', traceability);

console.log(`[bugs] Filed ${bugs.length} bugs. Severity breakdown:`, bugs.reduce((acc, b) => { acc[b.severity] = (acc[b.severity] || 0) + 1; return acc; }, {}));
